"""followers

Revision ID: 11249b6abe5e
Revises: 9dcc935a61e1
Create Date: 2023-09-11 16:01:19.524359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11249b6abe5e'
down_revision = '9dcc935a61e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
